### ISSUE TITLE
NPM registry

### ISSUE THREAD

**Issue by cellison** [pingidentity/pingone-sample-js#20]
I'm getting the following error with npm install.  Does not seem to be valid in the registry.npmjs.org anymore:
Not Found - GET https://registry.npmjs.org/@ping-identity/p14c-js-sdk-jwt/-/p14c-js-sdk-jwt-1.0.0-pre.1.tgz - Not found

**Comment by Plaoo** [comment]
same problem

**Comment by hkrop** [comment]
Yes , the  "@ping-identity/p14c-js-sdk-auth" is updated to "1.0.0-pre.2" version. The readme and package.json is updated due to this change.
Thanks @cellison for pointing the new version in your comment.
Please open a new issue if you find this not working.
